### ISSUE TITLE
Repo for Espressif FreeModbus support and questions?

### ISSUE THREAD

**Issue by brainstorm** [alisitsyn/modbus_support#3]
I've left some questions over https://esp32.com/viewtopic.php?f=13&t=26953, but I was wondering if this is your preferred place to receive them instead @alisitsyn?

**Comment by alisitsyn** [comment]
@brainstorm,

Thank you for your issue. Just need to complete some current tasks. I will take a look and answer your questions as soon as possible.

**Comment by brainstorm** [comment]
Thanks! Saw your reply, I'll try to find the chinese manual that came with the meter and come back to you in the esp32.com forums.

Cheers!
